repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
      - id: black
        name: black
        entry: black
        language: system
        types_or: [python, pyi]
